# coding: utf-8

"""
    Fleet v2 HTTP API

    HTTP-based API for Fleet Protocol v2 serving for communication between the External Server and the end users.

    The version of the OpenAPI document: 2.2.0
    Contact: jiri.strouhal@bringauto.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fleet_http_client_python.models.device_id import DeviceId

class TestDeviceId(unittest.TestCase):
    """DeviceId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeviceId:
        """Test DeviceId
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeviceId`
        """
        model = DeviceId()
        if include_optional:
            return DeviceId(
                module_id = 0,
                type = 0,
                role = 'p',
                name = ''
            )
        else:
            return DeviceId(
                module_id = 0,
                type = 0,
                role = 'p',
                name = '',
        )
        """

    def testDeviceId(self):
        """Test DeviceId"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
