# coding: utf-8

"""
    Fleet v2 HTTP API

    HTTP-based API for Fleet Protocol v2 serving for communication between the External Server and the end users.

    The version of the OpenAPI document: 2.2.0
    Contact: jiri.strouhal@bringauto.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fleet_http_client_python.models.available_devices import AvailableDevices

class TestAvailableDevices(unittest.TestCase):
    """AvailableDevices unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AvailableDevices:
        """Test AvailableDevices
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AvailableDevices`
        """
        model = AvailableDevices()
        if include_optional:
            return AvailableDevices(
                module_id = 47,
                device_list = [{module_id=47, type=2, role=test_device, name=Test Device}, {module_id=47, type=2, role=test_device, name=Test Device}]
            )
        else:
            return AvailableDevices(
                module_id = 47,
                device_list = [{module_id=47, type=2, role=test_device, name=Test Device}, {module_id=47, type=2, role=test_device, name=Test Device}],
        )
        """

    def testAvailableDevices(self):
        """Test AvailableDevices"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
