# coding: utf-8

"""
    Fleet v2 HTTP API

    HTTP-based API for Fleet Protocol v2 serving for communication between the External Server and the end users.

    The version of the OpenAPI document: 2.2.0
    Contact: jiri.strouhal@bringauto.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fleet_http_client_python.api.car_api import CarApi


class TestCarApi(unittest.TestCase):
    """CarApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CarApi()

    def tearDown(self) -> None:
        pass

    def test_available_cars(self) -> None:
        """Test case for available_cars

        """
        pass


if __name__ == '__main__':
    unittest.main()
