# coding: utf-8

# flake8: noqa
"""
    Fleet v2 HTTP API

    HTTP-based API for Fleet Protocol v2 serving for communication between the External Server and the end users.

    The version of the OpenAPI document: 2.4.1
    Contact: jiri.strouhal@bringauto.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from fleet_http_client_python.models.available_devices import AvailableDevices
from fleet_http_client_python.models.car import Car
from fleet_http_client_python.models.device_id import DeviceId
from fleet_http_client_python.models.message import Message
from fleet_http_client_python.models.module import Module
from fleet_http_client_python.models.payload import Payload
from fleet_http_client_python.models.payload_data import PayloadData
